DROP TABLE IF EXISTS company;

CREATE TABLE company
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
  name VARCHAR(30) NULL DEFAULT NULL COMMENT '名称',
  code VARCHAR(10) NULL DEFAULT NULL COMMENT '编码',
  PRIMARY KEY (id)
);